---
- name: enable ports in firewalld
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "{{ zbx_passive_port }}"
    - "{{ zbx_active_port }}"
  when:
    - "'firewalld' in ansible_facts.packages"
    - (ansible_facts.services['firewalld']['state'] in ['running', 'stopped'])

- name: allow ports in ufw
  shell: |
    'ufw allow in {{ zbx_passive_port }}/tcp'
    'ufw allow out {{ zbx_active_port }}/tcp'
  when:
    - "'ufw' in ansible_facts.packages"
    - (ansible_facts.services['ufw']['state'] in ['running', 'stopped'])
