---
- name: enable ports in firewalld
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "{{ zbx_passive_port }}"
    - "{{ zbx_active_port }}"
  when:
    - "'firewalld' in ansible_facts.packages"
    - ansible_facts.services['firewalld']['state'] == 'running'

- name: allow ports in ufw
  shell: |
    'ufw allow in {{ zbx_passive_port }}/tcp' \
    'ufw allow out {{ zbx_active_port }}/tcp'
  when:
    - "'ufw' in ansible_facts.packages"
    - ansible_facts.services['ufw']['state'] == 'running'

- shell: ufw status
  regist: ufw_status
- debug: msg={{ ufw_status }}
