---
- name: add Zabbix zypper repository
  zypper_repository:
    name: zabbix
    repo: 'https://repo.zabbix.com/zabbix/{{ zbx_version }}/sles/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/'
    auto_import_keys: true
    state: present
    runrefresh: true

- name: install zabbix-agent package
  package:
    name: "zabbix-agent={{ zbx_spec_version }}"
    state: present
