---
###### REDHAT ######
- block:
  
  - name: import Zabbix repo GPG key from url
    rpm_key:
      key: https://repo.zabbix.com/zabbix-official-repo.key
      state: present
  
  - name: add Zabbix yum repository # rhel
    yum_repository:
      name: zabbix
      description: zabbix {{ zbx_version }} yum repository
      baseurl: https://repo.zabbix.com/zabbix/{{ zbx_version }}/rhel/$releasever/$basearch/
      gpgcheck: no
      enabled: yes
  
  - name: update cache
    command: yum makecache
    args:
      warn: false
  
  when: ansible_os_family == "RedHat"

###### DEBIAN ######
- block:
  
  - name: import Zabbix repo GPG key from url
    apt_key:
      url: https://repo.zabbix.com/zabbix-official-repo.key
      state: present
  
  - name: add Zabbix apt repository (amd64) # ubuntu/debian
    apt_repository:
      repo: "deb [arch=amd64] https://repo.zabbix.com/zabbix/{{ zbx_version }}/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main"
      filename: zabbix
      update_cache: yes
      state: present
    when: ansible_architecture == "x86_64"
  
  - name: add Zabbix apt repository (arm64) # raspbian
    apt_repository:
      repo: "deb [arch=arm64] https://repo.zabbix.com/zabbix/{{ zbx_version }}/{{ ansible_lsb.id|lower }} {{ ansible_distribution_release }} main"
      filename: zabbix
      update_cache: yes
      state: present
    when:
      - ansible_lsb.id == "Raspbian"
      - ansible_architecture == "aarch64"
  
  - name: add Zabbix apt repository (arm64) # ubuntu-arm64
    apt_repository:
      repo: "deb [arch=arm64] https://repo.zabbix.com/zabbix/{{ zbx_version }}/{{ ansible_distribution|lower }}-arm64 {{ ansible_distribution_release }} main"
      filename: zabbix
      update_cache: yes
      state: present
    when:
      - ansible_distribution == "Ubuntu"
      - ansible_architecture == "aarch64"

  when: ansible_os_family == "Debian"

###### SUSE ######
- block:

  - name: add Zabbix zypper repository # sles
    zypper_repository:
      name: zabbix
      repo: 'https://repo.zabbix.com/zabbix/{{ zbx_version }}/sles/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/'
      auto_import_keys: true
      state: present
      runrefresh: true

  when: ansible_os_family == "Suse"

